version: "3.3"
services:
  database:
    image: "mysql:8.1.0"
    container_name: "dev_db_mysql"
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "password" 
    ports:
      - "3306:3306"